# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "owl"
version = "0.1.0"
edition = "2024"
description = "Chess engine built by me in Rust :)"
repository = "https://github.com/Jan-Frase/owl"
license = "Apache-2.0"

[features]
# This enables various stats to be gathered and printed as `info string ...`
dev = []

[dependencies]
mouse = { git = "https://github.com/Jan-Frase/mouse.git" }
